### ISSUE TITLE
npm install failing on github repository

### ISSUE THREAD

**Issue by BarryThePenguin** [ehmicky/gulp-execa#2]
Running `npm install gulp-execa` is hanging while looking for `sindresorhus/execa`

Changing the reference to

```
"execa": "https://github.com/sindresorhus/execa",
```

fixes the issue, so it may be a problem with my local environment, or git setup. It could also be an issue with the npm cli. Or even github itseful.

I'm not entirely sure where the problem is, so I'm starting by opening a pull request here

**Steps to reproduce**

Run `npm install --loglevel=silly gulp-execa` in an npm project

The install gets stuck trying to 

`git ls-remote -h -t git://github.com/sindresorhus/execa.git`

```
npm sill pacote Retrying git command: ls-remote -h -t git://github.com/sindresorhus/execa.git attempt # 2
npm sill pacote Retrying git command: ls-remote -h -t git://github.com/sindresorhus/execa.git attempt # 3
```

**Expected behavior**

`npm install gulp-execa` should install successfully

**Environment**

```
  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 554.00 MB / 16.00 GB
    Shell: 5.6.2 - /usr/local/bin/zsh
  Binaries:
    Node: 10.15.0 - ~/.asdf/installs/nodejs/10.15.0/bin/node
    Yarn: 1.16.0 - ~/.asdf/installs/nodejs/10.15.0/.npm/bin/yarn
    npm: 6.4.1 - ~/.asdf/installs/nodejs/10.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 66.0.5
    Safari: 12.0.3
    Safari Technology Preview: 13.0
```

**Comment by BarryThePenguin** [comment]
It looks like there's been some activity in `pacote ` around installing git repositories?

https://github.com/zkat/pacote/pull/172
https://github.com/zkat/pacote/pull/136
https://github.com/zkat/pacote/pull/172

I'll open an issue there and reference this

**Comment by ehmicky** [comment]
Thanks a lot for reporting this. 

The repository relies on several features brought by the next major release of `execa`, which is why the git commit hash is hard-coded. We are getting closer to releasing it.

I am also experiencing issue though with this approach, namely `npm audit` [does not work anymore](https://npm.community/t/npm-audit-fails-when-installing-dependencies-via-commit-hash/7860). It seems like `npm` is not handling that pattern very well.

To fix this problem, I am considering making an alpha release of `execa`: see the [issue here](https://github.com/sindresorhus/execa/issues/295).

**Comment by BarryThePenguin** [comment]
Running

```
npm install "https://github.com/sindresorhus/execa#6c0a40036ad602a64b4b50d9bf2638ec57c73fa3"
```

Works for me. It's installed as

```
"execa": "git+https://github.com/sindresorhus/execa.git#6c0a40036ad602a64b4b50d9bf2638ec57c73fa3",
```

**Comment by ehmicky** [comment]
I have just published [`0.7.1`](https://github.com/ehmicky/gulp-execa/releases/tag/0.7.1) with your suggestion (adding `git+https://github.com`). Can you check if this works for you?

**Comment by ehmicky** [comment]
`execa@2.0.0-alpha.0` has been published. I have published `8.0.0` with this alpha release, which should solve your issue. Please let me know if this does not fix it.

**Comment by BarryThePenguin** [comment]
Looking good now. Thanks for helping out 👍

**Comment by ehmicky** [comment]
Great! :tada:

**Comment by ehmicky** [comment]
@all-contributors please add @BarryThePenguin for finding out that bug!
